[tool.poetry]
name = "thlink-backend-object-storage-lib"
version = "0.2.0"
description = "S3 Wrapper"
authors = ["thlink"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.17.78"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
