[tool.poetry]
name = "autodeploy-tests"
version = "2.0.1-dev.1622743132"
description = ""
authors = ["Marco Acierno <marcoaciernoemail@gmail.com>"]
packages = [ { include = "autodeploy-tests" } ]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopub]
git-username = "Marcotte"
git-email = "marcotte@marcotte.house"
project-name = "ğŸ‹"
append-github-contributor = true

