[package]
name = "fizzbuzz_rust"
version = "0.1.0"
edition = "2018"
authors = ["Megumin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
name = "fizzbuzz_rust"
crate-type = ["cdylib"]

[package.metadata.maturin]
classifier = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]
