[tool.poetry]
name = "arcane-spreadsheet"
version = "0.3.0"
description = "Arcane spreadsheet tools"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"

google-api-python-client = "1.7.8"
oauth2client = "4.1.3"
arcane-core = "^1.0.7"
arcane-requests = "^0.1.2"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
